# Generated by Django 4.2 on 2025-01-14 04:33

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('TIPO_CUENTA', 'Tipo de Cuenta'), ('TIPO_TRANSACCION', 'Tipo de Transacción'), ('ESTADO_TARJETA', 'Estado de Tarjeta')], max_length=50, verbose_name='Categoría')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=20, unique=True, verbose_name='Número de Cuenta')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Disponible')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='La cédula debe tener al menos 10 dígitos.'), django.core.validators.RegexValidator('^\\d+$', message='La cédula debe contener solo números.')], verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='El número de teléfono debe tener al menos 10 dígitos.'), django.core.validators.RegexValidator('^\\d+$', message='El número de teléfono debe contener solo números.')], verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id_transacciones', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la Transacción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de la Transacción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Transacción')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_destino', to='cajero.cuentabancaria', verbose_name='Cuenta de Destino')),
                ('cuenta_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_emision', to='cajero.cuentabancaria', verbose_name='Cuenta de Emisión')),
                ('tipo_transaccion', models.ForeignKey(limit_choices_to={'categoria': 'TIPO_TRANSACCION'}, on_delete=django.db.models.deletion.CASCADE, to='cajero.catalogo', verbose_name='Tipo de transaccion')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16, message='El número de la tarjeta debe tener exactamente 16 dígitos.'), django.core.validators.RegexValidator('^\\d+$', message='El número de la tarjeta debe contener solo números.')], verbose_name='Número de Tarjeta')),
                ('fecha_emision', models.DateField(default=datetime.date.today, verbose_name='Fecha de Emisión')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de Caducidad')),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4, message='El PIN debe tener 4 dígitos.'), django.core.validators.RegexValidator('^\\d+$', message='El PIN debe contener solo números.')], verbose_name='PIN')),
                ('cuenta_perteneciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='cajero.usuario', verbose_name='Cuenta Perteneciente')),
                ('estado_tarjeta', models.ForeignKey(limit_choices_to={'categoria': 'ESTADO_TARJETA'}, on_delete=django.db.models.deletion.CASCADE, to='cajero.catalogo', verbose_name='Estado de Tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cajero.usuario', verbose_name='Nombre del Propietario'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='tipo_cuenta',
            field=models.ForeignKey(limit_choices_to={'categoria': 'TIPO_CUENTA'}, on_delete=django.db.models.deletion.CASCADE, to='cajero.catalogo', verbose_name='Tipo de Cuenta'),
        ),
    ]
