# Generated by Django 4.2 on 2025-01-14 06:14

from django.db import migrations
    
def populate_catalogo(apps, schema_editor):
    
    Catalogo = apps.get_model('cajero', 'Catalogo')
    
    Catalogo.objects.create(categoria='ESTADO_TARJETA', nombre='Activa', activo=True)
    Catalogo.objects.create(categoria='ESTADO_TARJETA', nombre='Bloqueada', activo=True)
    Catalogo.objects.create(categoria='ESTADO_TARJETA', nombre='Expirada', activo=True)
    Catalogo.objects.create(categoria='ESTADO_TARJETA', nombre='Inactiva', activo=True)

    Catalogo.objects.create(categoria='TIPO_CUENTA', nombre='Ahorros', activo=True)
    Catalogo.objects.create(categoria='TIPO_CUENTA', nombre='Corriente', activo=True)
    Catalogo.objects.create(categoria='TIPO_CUENTA', nombre='Nómina', activo=True)
    Catalogo.objects.create(categoria='TIPO_CUENTA', nombre='Inversiones', activo=True)

    Catalogo.objects.create(categoria='TIPO_TRANSACCION', nombre='Retiro', activo=True)
    Catalogo.objects.create(categoria='TIPO_TRANSACCION', nombre='Depósito', activo=True)
    Catalogo.objects.create(categoria='TIPO_TRANSACCION', nombre='Consulta', activo=True)
    Catalogo.objects.create(categoria='TIPO_TRANSACCION', nombre='Transferencia', activo=True)

class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_catalogo),
    ]
