# Generated by Django 4.2 on 2025-01-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0002_auto_20250114_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentabancaria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transacciones',
            options={},
        ),
        migrations.AddIndex(
            model_name='cuentabancaria',
            index=models.Index(fields=['numero_cuenta'], name='cajero_cuen_numero__0794d4_idx'),
        ),
        migrations.AddIndex(
            model_name='tarjeta',
            index=models.Index(fields=['numero_tarjeta'], name='cajero_tarj_numero__e30b29_idx'),
        ),
        migrations.AddIndex(
            model_name='transacciones',
            index=models.Index(fields=['id_transacciones'], name='cajero_tran_id_tran_f873aa_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cedula'], name='cajero_usua_cedula_e12fbd_idx'),
        ),
    ]
